# DB (Docker expuesta en tu PC)
spring.datasource.url=jdbc:mysql://localhost:3307/foro_hub?serverTimezone=UTC
spring.datasource.username=forohub
spring.datasource.password=forohub

# Forzamos Flyway (evita que agarre root de otro lado)
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

catalogo.upload-dir=uploads
spring.web.resources.static-locations=classpath:/static/,file:uploads/

api.security.secret=${API_SECURITY_SECRET:dev_secret}
