spring.application.name=foro.hub.api
spring.datasource.url=jdbc:mysql://localhost/foro_hub
spring.datasource.username=root
spring.datasource.password=sacha122
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.profiles.active=dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
springdoc.swagger-ui.persist-authorization=true

# --- ACTUATOR / MANAGEMENT ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers,threaddump,heapdump,env
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
management.info.git.mode=full
info.app.name=Foro Hub API
info.app.description=API REST con Spring Boot y JWT
info.app.version=1.0.0

server.error.include-stacktrace=never




api.security.secret=170517

# Rate limit (default)
app.ratelimit.enabled=true
app.ratelimit.loginMax=100
app.ratelimit.writeMax=300
app.ratelimit.readMax=1200
app.ratelimit.windowSeconds=600