ALTER TABLE respuesta_hija
    ADD COLUMN editado BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE respuesta
    ADD COLUMN editado BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE topico
    ADD COLUMN editado BOOLEAN NOT NULL DEFAULT FALSE;

